# Generated by Django 3.1 on 2020-08-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='email',
            new_name='userid',
        ),
    ]
